apiVersion: apps/v1
kind: Deployment
metadata:
  name: mag-provisioning
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mag-provisioning
  template:
    metadata:
      labels:
        app: mag-provisioning
    spec:
      containers:
        - name: mag-provisioning
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000