apiVersion: v1
kind: Service
metadata:
  name: mag-provisioning
spec:
  selector:
    app: mag-provisioning
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000